# https://github.com/marketplace/actions/upload-a-release-asset
name: Release
on:
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

    - name: Wait Arch Linux build
      uses: fountainhead/action-wait-for-check@v1.0.0
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: "arch-linux"

    - name: Download Arch Linux package
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: c-cpp.yml
        name: arch_package
        commit: ${{ github.sha }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Get Arch name
      id: arch
      run: echo ::set-output name=arch::$(ls *.pkg.tar.*)

    - name: Upload Arch Linux package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ steps.arch.outputs.arch }}
        asset_name: ${{ steps.arch.outputs.arch }}
        asset_content_type: application/zstd
